import type { Vehicle } from "./types";

/**
 * Sample inventory for Towns Auto.
 *
 * This data serves two purposes:
 *  1. It is loaded into Supabase by `supabase/seed.sql` (kept in sync manually).
 *  2. It is the offline fallback used by `lib/vehicles.ts` when Supabase is not
 *     yet configured, so the site looks complete out of the box.
 *
 * Replace these with real listings (and photos) through the /admin dashboard.
 */
function slugify(s: string) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

type Seed = Omit<Vehicle, "slug" | "created_at"> & { created_at?: string };

const seed: Seed[] = [
  {
    id: "11111111-0000-0000-0000-000000000001",
    year: 2021,
    make: "Honda",
    model: "Accord",
    trim: "EX Sedan",
    body_type: "Sedan",
    price: 9800,
    down_payment: 800,
    mileage: 41000,
    condition: "Excellent",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "FWD",
    exterior_color: "Modern Steel",
    interior_color: "Black",
    vin: "1HGCV1F1XMA000001",
    description:
      "Clean, well-maintained 2021 Honda Accord EX. One owner, smooth ride, excellent fuel economy. Loaded with Apple CarPlay, lane-keep assist, and a sunroof.",
    features: ["Apple CarPlay", "Sunroof", "Lane-Keep Assist", "Backup Camera", "Heated Seats"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: true,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000002",
    year: 2019,
    make: "Toyota",
    model: "Camry",
    trim: "SE",
    body_type: "Sedan",
    price: 8500,
    down_payment: 700,
    mileage: 58000,
    condition: "Excellent",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "FWD",
    exterior_color: "Celestial Silver",
    interior_color: "Black",
    vin: "4T1B11HK1KU000002",
    description:
      "Reliable 2019 Toyota Camry SE with sport-tuned suspension and a fuel-sipping 4-cylinder. Great first car or daily commuter.",
    features: ["Apple CarPlay", "Android Auto", "Backup Camera", "Bluetooth", "Alloy Wheels"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: true,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000003",
    year: 2020,
    make: "Honda",
    model: "Civic",
    trim: "Sport",
    body_type: "Sedan",
    price: 7900,
    down_payment: 700,
    mileage: 49000,
    condition: "Very Good",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "FWD",
    exterior_color: "Rallye Red",
    interior_color: "Black",
    vin: "2HGFC2F5XLH000003",
    description:
      "Sporty 2020 Honda Civic Sport with low miles for the year. Fun to drive, great on gas, and packed with tech.",
    features: ["Apple CarPlay", "Backup Camera", "Touchscreen", "Keyless Entry"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: true,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000004",
    year: 2018,
    make: "Ford",
    model: "F-150",
    trim: "XLT SuperCrew",
    body_type: "Truck",
    price: 14500,
    down_payment: 1200,
    mileage: 78000,
    condition: "Very Good",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "4WD",
    exterior_color: "Oxford White",
    interior_color: "Gray",
    vin: "1FTEW1EP8JK000004",
    description:
      "Capable 2018 Ford F-150 XLT SuperCrew with 4WD and the 2.7L EcoBoost. Tow package, bed liner, and plenty of room for the crew.",
    features: ["4WD", "Tow Package", "Bed Liner", "Backup Camera", "Apple CarPlay"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: true,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000005",
    year: 2017,
    make: "Toyota",
    model: "RAV4",
    trim: "XLE",
    body_type: "SUV",
    price: 11900,
    down_payment: 1000,
    mileage: 86000,
    condition: "Very Good",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "AWD",
    exterior_color: "Magnetic Gray",
    interior_color: "Black",
    vin: "JTMRFREV0HD000005",
    description:
      "Dependable 2017 Toyota RAV4 XLE with all-wheel drive. Roomy, comfortable, and ready for any season.",
    features: ["AWD", "Sunroof", "Backup Camera", "Bluetooth", "Power Liftgate"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: false,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000006",
    year: 2016,
    make: "BMW",
    model: "3 Series",
    trim: "328i",
    body_type: "Sedan",
    price: 10500,
    down_payment: 1000,
    mileage: 92000,
    condition: "Good",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "RWD",
    exterior_color: "Jet Black",
    interior_color: "Beige",
    vin: "WBA8E9G50GN000006",
    description:
      "Luxury on a budget: 2016 BMW 328i with leather seats, sunroof, and a punchy turbocharged engine. Well cared for.",
    features: ["Leather Seats", "Sunroof", "Navigation", "Heated Seats", "Premium Audio"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: false,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000007",
    year: 2019,
    make: "Nissan",
    model: "Altima",
    trim: "2.5 S",
    body_type: "Sedan",
    price: 7600,
    down_payment: 600,
    mileage: 64000,
    condition: "Very Good",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "FWD",
    exterior_color: "Gun Metallic",
    interior_color: "Charcoal",
    vin: "1N4BL4BV0KC000007",
    description:
      "Comfortable and efficient 2019 Nissan Altima. Spacious interior, smooth CVT, and great highway mileage.",
    features: ["Backup Camera", "Bluetooth", "Push-Button Start", "Apple CarPlay"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: false,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000008",
    year: 2020,
    make: "Jeep",
    model: "Grand Cherokee",
    trim: "Laredo",
    body_type: "SUV",
    price: 15900,
    down_payment: 1300,
    mileage: 61000,
    condition: "Excellent",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "4WD",
    exterior_color: "Diamond Black",
    interior_color: "Black",
    vin: "1C4RJFAG0LC000008",
    description:
      "Rugged and refined 2020 Jeep Grand Cherokee Laredo with 4WD. Great for family trips and light off-roading.",
    features: ["4WD", "Backup Camera", "Apple CarPlay", "Dual-Zone Climate", "Roof Rails"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: false,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000009",
    year: 2015,
    make: "Lexus",
    model: "ES 350",
    trim: "Base",
    body_type: "Sedan",
    price: 12500,
    down_payment: 1100,
    mileage: 99000,
    condition: "Good",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "FWD",
    exterior_color: "Pearl White",
    interior_color: "Tan",
    vin: "JTHBK1GG0F2000009",
    description:
      "Smooth, quiet, and loaded 2015 Lexus ES 350. Premium leather, navigation, and that legendary Lexus reliability.",
    features: ["Leather Seats", "Navigation", "Sunroof", "Heated & Cooled Seats", "Premium Audio"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: false,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000010",
    year: 2018,
    make: "Chevrolet",
    model: "Equinox",
    trim: "LT",
    body_type: "SUV",
    price: 9200,
    down_payment: 800,
    mileage: 72000,
    condition: "Very Good",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "FWD",
    exterior_color: "Silver Ice",
    interior_color: "Jet Black",
    vin: "2GNAXJEV0J6000010",
    description:
      "Practical 2018 Chevrolet Equinox LT with great cargo space and a turbocharged engine. Perfect everyday SUV.",
    features: ["Backup Camera", "Apple CarPlay", "Android Auto", "Remote Start"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: false,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000011",
    year: 2021,
    make: "Hyundai",
    model: "Elantra",
    trim: "SEL",
    body_type: "Sedan",
    price: 8900,
    down_payment: 700,
    mileage: 38000,
    condition: "Excellent",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "FWD",
    exterior_color: "Phantom Black",
    interior_color: "Gray",
    vin: "5NPLM4AG0MH000011",
    description:
      "Like-new 2021 Hyundai Elantra SEL with low miles and remaining factory feel. Modern tech and excellent warranty history.",
    features: ["Apple CarPlay", "Android Auto", "Lane-Keep Assist", "Backup Camera", "Bluetooth"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: false,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000012",
    year: 2017,
    make: "Honda",
    model: "CR-V",
    trim: "EX",
    body_type: "SUV",
    price: 12900,
    down_payment: 1100,
    mileage: 81000,
    condition: "Very Good",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "AWD",
    exterior_color: "Modern Steel",
    interior_color: "Gray",
    vin: "2HKRW2H59HH000012",
    description:
      "Spacious and reliable 2017 Honda CR-V EX with AWD and a sunroof. One of the most trusted compact SUVs on the road.",
    features: ["AWD", "Sunroof", "Apple CarPlay", "Backup Camera", "Heated Seats"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: false,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000013",
    year: 2016,
    make: "Ford",
    model: "Mustang",
    trim: "EcoBoost Premium",
    body_type: "Coupe",
    price: 13500,
    down_payment: 1200,
    mileage: 67000,
    condition: "Good",
    fuel_type: "Gasoline",
    transmission: "Manual",
    drivetrain: "RWD",
    exterior_color: "Race Red",
    interior_color: "Ebony",
    vin: "1FA6P8TH0G5000013",
    description:
      "Fun 2016 Ford Mustang EcoBoost Premium with a 6-speed manual. Turbocharged thrills and surprising fuel economy.",
    features: ["6-Speed Manual", "Leather Seats", "Backup Camera", "Premium Audio", "Sport Mode"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: false,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000014",
    year: 2019,
    make: "Subaru",
    model: "Outback",
    trim: "2.5i Premium",
    body_type: "Wagon",
    price: 13900,
    down_payment: 1200,
    mileage: 70000,
    condition: "Very Good",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "AWD",
    exterior_color: "Crystal Black",
    interior_color: "Slate Black",
    vin: "4S4BSAFC0K3000014",
    description:
      "Adventure-ready 2019 Subaru Outback Premium with standard AWD and EyeSight safety tech. Great for road trips.",
    features: ["AWD", "EyeSight Safety", "Apple CarPlay", "Heated Seats", "Roof Rails"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: false,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000015",
    year: 2020,
    make: "Kia",
    model: "Sportage",
    trim: "LX",
    body_type: "SUV",
    price: 11500,
    down_payment: 1000,
    mileage: 55000,
    condition: "Excellent",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "FWD",
    exterior_color: "Snow White Pearl",
    interior_color: "Black",
    vin: "KNDPMCAC0L7000015",
    description:
      "Stylish and efficient 2020 Kia Sportage LX. Comfortable interior, strong warranty history, and easy to drive.",
    features: ["Apple CarPlay", "Android Auto", "Backup Camera", "Bluetooth", "Alloy Wheels"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: false,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000016",
    year: 2014,
    make: "Toyota",
    model: "Tacoma",
    trim: "PreRunner V6",
    body_type: "Truck",
    price: 16500,
    down_payment: 1400,
    mileage: 112000,
    condition: "Good",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "RWD",
    exterior_color: "Super White",
    interior_color: "Graphite",
    vin: "5TFJU4GN0EX000016",
    description:
      "Legendary reliability in this 2014 Toyota Tacoma PreRunner V6. Holds its value, tows with ease, and built to last.",
    features: ["Tow Package", "Bed Liner", "Backup Camera", "Bluetooth", "Alloy Wheels"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: false,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000017",
    year: 2018,
    make: "Volkswagen",
    model: "Jetta",
    trim: "SE",
    body_type: "Sedan",
    price: 7200,
    down_payment: 600,
    mileage: 76000,
    condition: "Good",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "FWD",
    exterior_color: "Platinum Gray",
    interior_color: "Titan Black",
    vin: "3VWDB7AJ0JM000017",
    description:
      "Affordable and refined 2018 Volkswagen Jetta SE. German engineering, comfortable seats, and great gas mileage.",
    features: ["Sunroof", "Heated Seats", "Apple CarPlay", "Backup Camera", "Bluetooth"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: false,
    is_sold: false,
  },
  {
    id: "11111111-0000-0000-0000-000000000018",
    year: 2022,
    make: "Mazda",
    model: "CX-5",
    trim: "Touring",
    body_type: "SUV",
    price: 17900,
    down_payment: 1500,
    mileage: 33000,
    condition: "Excellent",
    fuel_type: "Gasoline",
    transmission: "Automatic",
    drivetrain: "AWD",
    exterior_color: "Soul Red Crystal",
    interior_color: "Black",
    vin: "JM3KFBCM0N0000018",
    description:
      "Upscale 2022 Mazda CX-5 Touring with AWD and low miles. Premium feel, sharp handling, and loaded with safety tech.",
    features: ["AWD", "Leatherette Seats", "Apple CarPlay", "Blind-Spot Monitor", "Heated Seats"],
    images: [],
    warranty: "90-Day Warranty",
    is_featured: true,
    is_sold: false,
  },
];

export const sampleVehicles: Vehicle[] = seed.map((v) => ({
  ...v,
  slug: slugify(`${v.year}-${v.make}-${v.model}-${v.trim ?? ""}-${v.id.slice(-4)}`),
  created_at: v.created_at ?? "2026-01-01T00:00:00.000Z",
}));
